version: '3.1'

services:
    react:
        container_name: react
        hostname: react
        build: 
            context: ./
            dockerfile: ./DockerfileReact
        image: react:1.1
        ports:
            - "3025:3000"
        volumes:
            - ./react:/home/app
    flask:
        container_name: react_flast
        hostname: react_flast
        build: 
            context: ./
            dockerfile: DockerfileFlask
        image: flask:1.1
        ports:
            - "8025:8000"
        volumes:
            - ./flask:/home/app/
    database:
        container_name: react_mysql
        hostname: react_mysql    
        image: mysql:5.7-debian
        user: "1000"
        ports:
            - "3326:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
        volumes:
            - ./db:/var/lib/mysql

